// Higher precision floating point numbers via expansion arithmetic
#pragma once

#include "expansion.h"

// Pull in autogenerated codelets
#include "gen-expansion.h"

namespace mandelbrot {

// int literals go through the mixed double codelets (exact for |a| < 2^53), rather than being ambiguous between
// the double and int64_t overloads
template<int n> __host__ __device__ static inline Expansion<n> operator*(const int a, const Expansion<n> x) {
  return double(a) * x;
}
template<int n> __host__ __device__ static inline Expansion<n> operator*(const Expansion<n> x, const int a) {
  return x * double(a);
}

// Comparisons with a double, as against the double padded with zeros: false for nan, like IEEE
template<int n> __host__ __device__ static inline int compare_double(const Expansion<n> x, const double y) {
  // 1, 0, -1 for x > y, x == y, x < y, and 2 if unordered
  if (x.x[0] != y) return x.x[0] > y ? 1 : x.x[0] < y ? -1 : 2;
  for (int i = 1; i < n; i++) if (x.x[i] != 0) return x.x[i] > 0 ? 1 : x.x[i] < 0 ? -1 : 2;
  return 0;
}
template<int n> __host__ __device__ static inline bool operator<(const Expansion<n> x, const double y) { return compare_double(x, y) == -1; }
template<int n> __host__ __device__ static inline bool operator>(const Expansion<n> x, const double y) { return compare_double(x, y) == 1; }
template<int n> __host__ __device__ static inline bool operator<=(const Expansion<n> x, const double y) {
  const int c = compare_double(x, y); return c == -1 || c == 0;
}
template<int n> __host__ __device__ static inline bool operator>=(const Expansion<n> x, const double y) {
  const int c = compare_double(x, y); return c == 1 || c == 0;
}
template<int n> __host__ __device__ static inline bool operator<(const double y, const Expansion<n> x) { return x > y; }
template<int n> __host__ __device__ static inline bool operator>(const double y, const Expansion<n> x) { return x < y; }

}  // namespace mandelbrot
