#!/usr/bin/env python3

from functools import partial
import re


def main():
  with open('README.tex.md') as f:
    text = f.read()

  def render(m, *, block: bool):
    latex = m.group(1)
    latex = latex.replace('+', '%2B')
    base = 'https://render.githubusercontent.com/render/math'
    def img(latex, mode):
      if mode == 'dark':
        latex = '\color{white}' + latex 
      if block:
        latex = '\displaystyle ' + latex
      return f'<img src="{base}?math={{{latex}}}#gh-{mode}-mode-only">'
    light = img(latex, 'light')
    dark = img(latex, 'dark')
    if block:
      return f'<p align="center">{light}{dark}</p>'
    else:
      return f'<span>{light}{dark}</span>'
    
  text = re.sub(r'\$\$(.*)\$\$', partial(render, block=True), text)
  text = re.sub(r'\$(.*)\$', partial(render, block=False), text)
  with open('README.md', 'w') as f:
    f.write(text)


if __name__ == '__main__':
  main()
