#!/bin/bash

cd "${0%/*}"  # Change to script directory
rm -rf build
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  export CXX=clang-13
else
  prefix=`brew --prefix`
  export CPPPATH=$prefix/include
  export LDPATH=$prefix/lib
  export CXX=$prefix/opt/llvm/bin/clang-13
fi
meson setup build/debug --buildtype=debug
CXXFLAGS='-O3 -march=native' meson setup build/release --buildtype=release
